---
driver:
  name: docker
  use_sudo: false
  chef_version: latest

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
- name: centos-7
  driver_config:
    image: centos/systemd
    run_command: /usr/sbin/init
    privileged: true
    provision_command:
      - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
      - systemctl enable sshd.service

suites:
  - name: default
    run_list:
      - recipe[sshkeys]
    data_bags_path: "test/databags"
    verifier:
      inspec_tests:
        - test/integration/default
